# Generated by Django 5.0.7 on 2024-08-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_abanaccount_consolidatedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidatedorder',
            name='orders',
        ),
        migrations.AddField(
            model_name='aggregatedorder',
            name='orders',
            field=models.ManyToManyField(related_name='aggregated_orders', to='exchange.order'),
        ),
        migrations.AlterField(
            model_name='aggregatedorder',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consolidatedorder',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
